project_id = "ibihfzhrsllndxhfwgvb"

[functions.og]
verify_jwt = false

[functions.create_countdown]
verify_jwt = true

[functions.moderate_countdown]
verify_jwt = true

[functions.out_redirect]
verify_jwt = false

[functions.import_liga1_fixtures]
verify_jwt = false

[functions.update_live_scores]
verify_jwt = false

[functions.match_lite]
verify_jwt = false

[functions.import_tmdb_movies]
verify_jwt = false

[functions.update_movie_providers]
verify_jwt = false

[functions.reminder_upsert]
verify_jwt = true

[functions.schedule_reminders]
verify_jwt = false

[functions.send_reminders]
verify_jwt = false

[functions.ics_event]
verify_jwt = false

[functions.ics_user_feed]
verify_jwt = false

[functions.weekly_digest]
verify_jwt = false

[functions.resend_webhook]
verify_jwt = false

[functions.email_render]
verify_jwt = false

[functions.email_send]
verify_jwt = false

[functions.aggregate_internal_metrics]
verify_jwt = false

[functions.build_trending]
verify_jwt = false

[functions.export_metrics_csv]
verify_jwt = false

[functions.collect_plausible_daily]
verify_jwt = false
