project_id = "ibihfzhrsllndxhfwgvb"

[functions.og]
verify_jwt = false

[functions.create_countdown]
verify_jwt = true

[functions.moderate_countdown]
verify_jwt = true

[functions.out_redirect]
verify_jwt = false
