export const routes = {
  home: () => "/",
  event: (slug: string) => `/evenimente/${slug}`,
  create: () => "/creeaza",
  category: (slug: string) => `/categorii/${slug}`,
  countdown: (id: string) => `/c/${id}`,
  embed: (id: string) => `/embed/${id}`,
  blackFriday: () => "/black-friday",
  blackFridayYear: (year: number | string) => `/black-friday/${year}`,
  blackFridayMerchant: (slug: string) => `/black-friday/${slug}`,
  blackFridayCategory: (slug: string) => `/black-friday/${slug}`,
  sport: () => "/sport",
  match: (matchId: string) => `/sport/${matchId}`,
  movies: () => "/filme",
  movie: (id: string) => `/filme/${id}`,
  search: (q?: string) => q ? `/cauta?q=${encodeURIComponent(q)}` : "/cauta",
  tag: (slug: string) => `/tag/${slug}`,
  team: (slug: string) => `/echipa/${slug}`,
  tv: (slug: string) => `/tv/${slug}`,
  about: () => "/despre",
  contact: () => "/contact",
  account: () => "/account",
  authLogin: (redirect?: string) => `/auth/login${redirect ? `?redirect=${encodeURIComponent(redirect)}` : ""}`,
  authCallback: () => "/auth/callback",
  legalTerms: () => "/legal/terms",
  legalPrivacy: () => "/legal/privacy",
  legalCookies: () => "/legal/cookies",
  admin: () => "/admin",
  adminModeration: () => "/admin/moderation",
  adminAppearance: () => "/admin/appearance",
  adminMetrics: () => "/admin/metrics",
  adminEmails: () => "/admin/emails",
};
