export const routes = {
  home: () => "/",
  event: (slug: string) => `/evenimente/${slug}`,
  create: () => "/creeaza",
  category: (slug: string) => `/categorii/${slug}`,
  countdown: (id: string) => `/c/${id}`,
  embed: (id: string) => `/embed/${id}`,
  blackFriday: () => "/black-friday",
  sport: () => "/sport",
  match: (matchId: string) => `/sport/${matchId}`,
  movies: () => "/filme",
  movie: (id: string) => `/filme/${id}`,
  about: () => "/despre",
  contact: () => "/contact",
  account: () => "/account",
  authLogin: (redirect?: string) => `/auth/login${redirect ? `?redirect=${encodeURIComponent(redirect)}` : ""}`,
  authCallback: () => "/auth/callback",
  legalTerms: () => "/legal/terms",
  legalPrivacy: () => "/legal/privacy",
  legalCookies: () => "/legal/cookies",
  admin: () => "/admin",
  adminModeration: () => "/admin/moderation",
  adminAppearance: () => "/admin/appearance",
  adminMetrics: () => "/admin/metrics",
};
