export const routes = {
  home: () => "/",
  event: (slug: string) => `/evenimente/${slug}`,
  create: () => "/creeaza",
  category: (slug: string) => `/categorii/${slug}`,
  countdown: (id: string) => `/c/${id}`,
  embed: (id: string) => `/embed/${id}`,
  blackFriday: () => "/black-friday",
  blackFridayYear: (year: number | string) => `/black-friday/${year}`,
  blackFridayMerchant: (slug: string) => `/black-friday/${slug}`,
  blackFridayCategory: (slug: string) => `/black-friday/${slug}`,
  sport: () => "/sport",
  match: (matchId: string) => `/sport/${matchId}`,
  movies: () => "/filme",
  moviesMonth: (year: string, month: string) => `/filme/${year}-${month}`,
  moviesPlatform: (platform: string) => `/filme/${platform}`,
  movie: (slug: string) => `/filme/${slug}`,
  search: (q?: string) => q ? `/cauta?q=${encodeURIComponent(q)}` : "/cauta",
  tag: (slug: string) => `/tag/${slug}`,
  team: (slug: string) => `/echipa/${slug}`,
  tv: (slug: string) => `/tv/${slug}`,
  tvGuide: () => "/tv",
  about: () => "/despre",
  contact: () => "/contact",
  account: () => "/account",
  authLogin: (redirect?: string) => `/auth/login${redirect ? `?redirect=${encodeURIComponent(redirect)}` : ""}`,
  authCallback: () => "/auth/callback",
  legalTerms: () => "/legal/terms",
  legalPrivacy: () => "/legal/privacy",
  legalCookies: () => "/legal/cookies",
  admin: () => "/admin",
  adminModeration: () => "/admin/moderation",
  adminAppearance: () => "/admin/appearance",
  adminMetrics: () => "/admin/metrics",
  adminEmails: () => "/admin/emails",
  // Liga 1 (SuperLiga)
  liga1: () => "/liga-1",
  superliga: () => "/superliga",
  liga1Table: () => "/liga-1/clasament",
  liga1Round: (nr: number | string) => `/liga-1/etapa/${nr}`,
  liga1Results: () => "/liga-1/rezultate",
  liga1Teams: () => "/liga-1/echipe",
  liga1Team: (slug: string) => `/liga-1/echipe/${slug}`,
};
